name: "Integration Testing"

on: [push]

# add another job that creates a new check suite using the API, send check suite id in our payload

jobs:
  dispatch-events:
    if: github.event.repository.full_name == 'github/codeql-action'
    runs-on: ubuntu-latest
    steps:
    - name: Send repository dispatch event
      run: |
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.CODEQL_TESTING_TOKEN }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          https://api.github.com/repos/Anthophila/amazon-cognito-js-copy/dispatches \
          -D '{"event_type":"codeql-integration","client_payload": {"sha": "${{ github.sha }}"}}'
    - name: Create check runs
      run: |
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.antiope-preview+json" \
          https://api.github.com/repos/github/codeql-action/check-runs \
          -D '{"name": "Integration Test Results", "head_sha": "${{ github.sha }}"}'
