name: "Integration Testing"

on: [push, pull_request]

# add another job that creates a new check suite using the API, send check suite id in our payload

jobs:
  dispatch-events:
    runs-on: ubuntu-latest
    steps:
    - uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets. CODEQL_TESTING_TOKEN }}
        repository: Anthophila/amazon-cognito-js-copy
        event-type: codeql-integration
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'