name: "TSLint"

on: [push]

jobs:
  tslint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: tslint
      run: |
        node_modules/.bin/tslint -c tslint.json 'src/**/*.ts'
